services:
  backend:
    build: ./server
      #context: ./backend
      #dockerfile: Dockerfile
    ports:
      - '5000:5000'
  frontend:
    build: ./client
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    depends_on:
      - backend