apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000 # Dış dünyaya açılacak port
    targetPort: 5000 # Container içinde çalışacak port
  type: LoadBalancer # Servis tipi (ClusterIP, NodePort, LoadBalancer)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1 # Uygulamanızın kaç kopyasının çalışacağını belirler
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: erenxcolakx/liweather-be:latest # Backend uygulamanızın Docker imajı
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 5000 # Backend uygulamanızın dinleyeceği port
        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000"


